/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef tutorial_CONSTANTS_H
#define tutorial_CONSTANTS_H

#include "tutorial_types.h"



class tutorialConstants {
 public:
  tutorialConstants();

};

extern const tutorialConstants g_tutorial_constants;



#endif
